//! The operator UI bundle, embedded in this executable.
//!
//! Every byte the mounted application needs is in the binary: the shell is
//! generated in `serve.rs` from the names below, and each asset is served
//! from `ASSETS` — never read from the filesystem, never fetched from a third
//! party (SPA-01). The table itself is generated by `build.rs` from the
//! committed `web/dist`, because the file names carry a content hash that
//! cannot be written down ahead of the build.
//!
//! `SHA256` is the whole bundle as one number. It is the second half of the
//! release proof (SPA-03): `kanban --version` prints it, the package receipt
//! records it as `bundleSha256`, and the install compares the two before it
//! commits.

include!(concat!(env!("OUT_DIR"), "/bundle_assets.rs"));

/// One embedded asset by the exact name the shell links, or nothing.
///
/// Exact: the name carries a content hash, so a request for a name that is
/// not in the table is a request for an asset this binary does not have — a
/// stale page, a typo, or a probe — and is answered as not found rather than
/// by guessing which file was meant.
pub(crate) fn asset(name: &str) -> Option<&'static Asset> {
    ASSETS.iter().find(|asset| asset.name == name)
}
